### ISSUE TITLE
Settings Page Fails to Load

### ISSUE THREAD

**Issue by SkyNinja** [Lacro59/playnite-screenshotsvisualizer-plugin#81]
When trying to access settings, nothing but the message "Failed to load settings" appears.
![Playnite DesktopApp_2NGrK5LmYr](https://github.com/Lacro59/playnite-screenshotsvisualizer-plugin/assets/4765557/2fc28559-00cd-430c-b2dd-d9ae4829435a)

There was nothing relevant to the plugin in extensions.log other than this line:
```24-06 22:54:38.816|INFO |ScreenshotsVisualizer#PluginDatabaseObject`4:LoadDatabase with 0 items - 00:06.71```

**Comment by Lacro59** [comment]
Nothing in Playnite.log?

**Comment by hunkyburrito** [comment]
I'm having the same issue and found the following in my logs.
<details>
<summary>Relevant lines in playnite.log</summary>

```
14-08 21:15:20.615|ERROR|PluginSettingsHelper:Failed to load plugin settings, c6c8276f-91bf-48e5-a1d1-4bee0b493488
System.NullReferenceException: Object reference not set to an instance of an object.
   at ScreenshotsVisualizer.Views.ScreenshotsVisualizerSettingsView.TabControl_SelectionChanged(Object sender, SelectionChangedEventArgs e) in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\Views\ScreenshotsVisualizerSettingsView.xaml.cs:line 628
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.TabControl.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedIndexChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
   at System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   at System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
   at System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.FrameworkElement.UpdateStyleProperty()
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.Controls.TabControl.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at System.Windows.Controls.ItemsControl.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   at System.Xaml.XamlObjectWriter.Logic_EndInit(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ScreenshotsVisualizer.Views.ScreenshotsVisualizerSettingsView.InitializeComponent() in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\Views\ScreenshotsVisualizerSettingsView.xaml:line 1
   at ScreenshotsVisualizer.Views.ScreenshotsVisualizerSettingsView..ctor() in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\Views\ScreenshotsVisualizerSettingsView.xaml.cs:line 33
   at ScreenshotsVisualizer.ScreenshotsVisualizer.GetSettingsView(Boolean firstRunSettings) in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\ScreenshotsVisualizer.cs:line 693
   at Playnite.DesktopApp.ViewModels.PluginSettingsHelper.GetPluginSettingsView(Guid pluginId, ExtensionFactory extensions, Dictionary`2 loadedPluginSettings) in C:\projects\playnite\source\Playnite.DesktopApp\PluginSettingsHelper.cs:line 42
```
</details>
<details>
<summary>Relevant line in extensions.log</summary>

``14-08 20:33:39.210|INFO |ScreenshotsVisualizer#PluginDatabaseObject`4:LoadDatabase with 14 items - 00:01.23``
</details>

**Comment by SkyNinja** [comment]
> Nothing in Playnite.log?

Forgot about this plugin and missed it at the time, but yes, the same as @hunkyburrito.

```
02-09 06:23:11.172|ERROR|PluginSettingsHelper:Failed to load plugin settings, c6c8276f-91bf-48e5-a1d1-4bee0b493488
System.NullReferenceException: Object reference not set to an instance of an object.
   at ScreenshotsVisualizer.Views.ScreenshotsVisualizerSettingsView.TabControl_SelectionChanged(Object sender, SelectionChangedEventArgs e) in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\Views\ScreenshotsVisualizerSettingsView.xaml.cs:line 628
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.TabControl.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedIndexChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
   at System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   at System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
   at System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.FrameworkElement.UpdateStyleProperty()
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.Controls.TabControl.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at System.Windows.Controls.ItemsControl.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   at System.Xaml.XamlObjectWriter.Logic_EndInit(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ScreenshotsVisualizer.Views.ScreenshotsVisualizerSettingsView.InitializeComponent() in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\Views\ScreenshotsVisualizerSettingsView.xaml:line 1
   at ScreenshotsVisualizer.Views.ScreenshotsVisualizerSettingsView..ctor() in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\Views\ScreenshotsVisualizerSettingsView.xaml.cs:line 33
   at ScreenshotsVisualizer.ScreenshotsVisualizer.GetSettingsView(Boolean firstRunSettings) in D:\GitHub\Lacro59\playnite-screenshotsvisualizer-plugin\source\ScreenshotsVisualizer.cs:line 693
   at Playnite.DesktopApp.ViewModels.PluginSettingsHelper.GetPluginSettingsView(Guid pluginId, ExtensionFactory extensions, Dictionary`2 loadedPluginSettings) in C:\projects\playnite\source\Playnite.DesktopApp\PluginSettingsHelper.cs:line 42
```
